services:
  - type: web
    name: text-to-speech-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MAX_TEXT_LENGTH
        value: 500
      - key: CORS_ORIGIN
        value: http://localhost:5173
